# Generated by Django 3.2.6 on 2021-08-17 11:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('language', models.CharField(choices=[('bn', 'Bengali'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('ja', 'Japanese'), ('zh', 'Chinese')], default='bn', max_length=2)),
                ('currency', models.CharField(choices=[('bdt', 'BDT'), ('usd', 'USD'), ('eur', 'EUR'), ('gbp', 'GBP'), ('cny', 'CNY'), ('jpy', 'JPY'), ('rub', 'RUB')], default='bdt', max_length=3)),
            ],
        ),
    ]
